config/routes.rb
Rails.application.routes.draw do
  
  resources :schedules
  root 'schedules#index'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true, length: { maximum: 20 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :memo, length: { maximum: 500 }
  validate :end_date_is_after_start_date

  private

  def end_date_is_after_start_date
    if end_date.present? && start_date.present? && end_date < start_date
      errors.add(:end_date, 'は開始日より後の日付でなければなりません')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :bio])
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[show edit update destroy]

  def index
    @schedules = Schedule.all
  end

  def show
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      flash[:notice] = "予定を新規登録しました"
      redirect_to :schedules
    else
      render :new
    end
  end

  def update
    if @schedule.update(schedule_params)
      flash[:notice] = "予定を更新しました"
      redirect_to :schedules
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @schedule.destroy
    flash[:notice] = "予定を削除しました"
    redirect_to :schedules
  end

  private

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def schedule_params
    params.require(:schedule).permit(:title, :start_date, :end_date, :all_day, :memo)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!, except: [:index, :show]

  def index
  end

  def show
    @user = current_user
  end

  def account
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>宿泊予約アプリ</h1>
      <nav>
       <% if user_signed_in? %>
        <div>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
          <%= link_to current_user.name,user_path(current_user) %>
        </div>
       <% else %>
        <ul>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
          <li><%= link_to '新規登録', new_user_registration_path %></li>
        </ul>
       <% end %>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/schedules/_form.html.erb
<!-- app/views/schedules/_form.html.erb -->
<%= form_with model: @schedule, local: true do |form| %>
    <div class="field">
      <%= form.label :title, "タイトル" %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :start_date, "開始日" %>
      <%= form.date_select :start_date %>
    </div>
  
    <div class="field">
      <%= form.label :end_date, "終了日" %>
      <%= form.date_select :end_date %>
    </div>
  
    <div class="field">
      <%= form.label :all_day, "終日" %>
      <%= form.check_box :all_day %>
    </div>
  
    <div class="field">
      <%= form.label :memo, "メモ" %>
      <%= form.text_area :memo %>
    </div>
  
    <div class="actions">
      <%= form.submit "登録完了する" %>
    </div>
  <% end %>

app/views/schedules/create.html.erb
<h1>Schedules#create</h1>
<p>Find me in app/views/schedules/create.html.erb</p>

app/views/schedules/destroy.html.erb
<h1>Schedules#destroy</h1>
<p>Find me in app/views/schedules/destroy.html.erb</p>

app/views/schedules/edit.html.erb
<!-- app/views/schedules/edit.html.erb -->
<h1>予定編集</h1>
<%= render partial: 'form', schedule: @schedule %>
<%= link_to '一覧に戻る', schedules_path %>

app/views/schedules/index.html.erb
<!-- app/views/schedules/index.html.erb -->
<h1>予定一覧</h1
<% if flash[:notice] %>
 <p class="notice"><%= flash[:notice] %></p>
<% end %>
<p>本日の日付: <%= Time.zone.now.strftime('%Y/%m/%d') %></p>
<p>予定の合計数: <%= @schedules.nil? ? 0 : @schedules.count %></p>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
    </tr>
  </thead>
  <tbody>
   <% if @schedules.present? %>
    <% @schedules.each do |schedule| %>
     <tr>
      <td><%= schedule.id %></td>
      <td><%= schedule.title %></td>
      <td><%= schedule.start_date.strftime('%Y/%m/%d') %></td>
      <td><%= schedule.end_date.strftime('%Y/%m/%d') %></td>
      <td><%= schedule.all_day ? '○' : '' %></td>
      <td><%= schedule.updated_at.to_s(:datetime_jpm) %></td>

      <td>
       <%= link_to '詳細', schedule %>
       <%= link_to '編集', edit_schedule_path(schedule) %>
       <%= link_to '削除', schedule, method: :delete, data: { confirm: "予定を削除しますか？"} %>
      </td>
     </tr>

   <% end %>
   <% else %>
    <p>予定がありません。</p>
   <% end %>

  </tbody>
<p><%= link_to '新規追加', new_schedule_path %></p>

app/views/schedules/new.html.erb
<!-- app/views/schedules/new.html.erb -->
<h1>新規予定追加</h1>
<%= render partial: 'form', schedule: @schedule %>
<%= render "shared/error", obj: @schedule %> 
<%= link_to '一覧に戻る', schedules_path %>

app/views/schedules/show.html.erb
<!-- app/views/schedules/show.html.erb -->
<h1>予定詳細</h1>
<p>タイトル: <%= @schedule.title %></p>
<p>開始日: <%= @schedule.start_date.strftime('%Y/%m/%d') %></p>
<p>終了日: <%= @schedule.end_date.strftime('%Y/%m/%d') %></p>
<p>終日: <%= @schedule.all_day ? '○' : '' %></p>
<p>スケジュールメモ: <%= @schedule.memo %></p>
<%= link_to '一覧に戻る', schedules_path %>
<%= link_to '編集', edit_schedule_path(@schedule) %>

app/views/schedules/update.html.erb
<h1>Schedules#update</h1>
<p>Find me in app/views/schedules/update.html.erb</p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
 <% obj.errors.full_messages.each do |message| %>
  <ul>
   <li><%= message %></li>
  </ul>
 <% end %>
 <% end %>

app/views/users/account.html.erb
<h1>Users#account</h1>
<p>Find me in app/views/users/account.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Usersコントローラー</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
    <h2>ユーザー詳細</h2>
    <p><strong>名前:</strong> <%= @user.name %></p>
    <p><strong>メールアドレス:</strong> <%= @user.email %></p>
    <p><strong>パスワード:</strong> *********</p>
    
    
    <%= link_to '戻る', users_path %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>